### ISSUE TITLE
Allow Ctrl+C for `keyInSelect`

### ISSUE THREAD

**Issue by walling** [anseki/readline-sync#50] opened 2017-01-20 13:33 UTC
It could be nice if Ctrl+C was allowed in `keyInSelect`, when the cancel option is available. Pressing Ctrl+C should be interpreted as cancel.

**Comment by anseki** [comment] 2017-01-20 16:02
Hi @walling, thank you for the comment.
It seems a duplicate of https://github.com/anseki/readline-sync/issues/42.

**Closed by anseki** 2017-01-20 16:02 UTC
