### ISSUE TITLE
Initial value set to the prompt as already typed once the user is asked for an input

### ISSUE THREAD

**Issue by philocoder** [anseki/readline-sync#55] opened 2017-03-10 14:19 UTC
Hello! This is my first "issue" xD so sorry if I get wrong in something.

First, I want to say: great job! This package is very useful.

Secondly, I wonder if something could be added so the developer could specify a value which could be already typed as answer once the question is thrown to the user. Like the "defaultInput" option, but another one, like "initialInputTyped", or something similar. This way, the developer can freely adapt the prompt's initial value, at the same time that the question is being made, to more specific purposes. But at the same time, also letting the final user remove it partially or totally.

Thank you anyway, great tool!!

**Comment by anseki** [comment] 2017-03-10 20:10
Hi @philocoder, thank you for the comment 😄 

So, do you mean that a limited list of choices?
Does the [`keyInSelect`](https://github.com/anseki/readline-sync#keyinselect) method help you?

Sorry, my English is poor. Please tell me if I mistook your words.

**Comment by philocoder** [comment] 2017-03-14 14:27
Hi @anseki! I didn't expect a reply so fast.

Mmmm... No, keyInSelect can't help me here. It would be mainly for prompt/question methods. Some property for the prompt/question methods, to initially set some text as user's input, so the user, when is asked for the input, can see it, and manipulate it before answering. Like a pre-defined and already-typed answer, which is not definitive, but is used to type from it the final answer.

Like what happens when we type *tabulation* from the command line while searching for some path. The command line shows some valid paths, but the text that was in the command line already typed, as input user, remains there. That effect is what I want to achieve, and I missed some property like "initialValue" or similar, in order to trigger the question, but with a pre-stablished answer (which in the example of the command line, would be the already typed by the user before typing the tabulation).

And sorry for my English, it's poor... Let me know if something is not well said or unclear.

**Comment by anseki** [comment] 2017-03-14 18:03
I see, you might want something like TUI.
It might be a duplicate of https://github.com/anseki/readline-sync/issues/46 and https://github.com/anseki/readline-sync/issues/16.
And ncurses may help you.

**Comment by philocoder** [comment] 2017-03-14 20:12
Ohhh okay, hehehe I see I'm not the first one. Thank you then. I'll check it out them then

**Comment by anseki** [comment] 2017-03-15 07:22
I hope the ncurses or another library helps you even if readlineSync can't help you.
So, please close this issue if it was solved, and please comment to #16 if you want, about the editable default input value.

**Comment by anseki** [comment] 2017-03-21 10:20
Unfortunately, no reply came, and I close this issue.

**Closed by anseki** 2017-03-21 10:20 UTC
