### ISSUE TITLE
backspace not working in hideEchoBack true

### ISSUE THREAD

**Issue by raghav135** [anseki/readline-sync#41] opened 2016-07-01 10:44 UTC
script
var rl = require('readline-sync');

var secret = rl.question('Enter secret: ', { hideEchoBack: true });
console.log(secret);

Type a [backspace] b

output is ab.

Can you tell me if i am missing something?

**Comment by anseki** [comment] 2016-07-01 11:40
Hi @raghav135,
This is a duplicate of https://github.com/anseki/readline-sync/issues/17 .

**Closed by anseki** 2016-07-01 11:40 UTC
