### ISSUE TITLE
Problem with chalk on Windows 7 platform

### ISSUE THREAD

**Issue by WolfgangWakolbinger** [anseki/readline-sync#45] opened 2016-09-15 06:50 UTC
Using chalk together with readlineSync.question() does not change the color. I have the following code:
`let name = readlineSync.question(chalk.red('Your name: '));`
Which produces the following result on Windows command line:
`←[31mYour name: ←[39m`
I use the following system environment:
- Windows 7 32bit
- node 6.5.0
- readline-sync 1.4.4
- chalk 1.1.3

**Comment by anseki** [comment] 2016-09-15 10:15
Hi @WolfgangWakolbinger,
It seems duplicate of https://github.com/anseki/readline-sync/issues/32.

**Closed by anseki** 2016-09-15 10:15 UTC
