### ISSUE TITLE
SIGSEGV on ^C to exit

### ISSUE THREAD

**Issue by thejameskyle** [anseki/readline-sync#29] opened 2016-02-01 22:18 UTC
I've been unable to figure out exactly why, but for some reason hitting `^C` to exit `readlineSync.question()` will result in the process hanging forever.

This is the code it takes to reproduce.

```js
var readline = require('readline-sync');

process.on('SIGSEGV', function() {
  console.log('hi');
});

readline.question('Hit ^C to exit (this will then hang forever)');
```

Repo for this here: https://github.com/thejameskyle/__readline-sync-test

Found this while using the [`signal-exit`](https://www.npmjs.com/package/signal-exit) module as a sub-dependency.

**Comment by anseki** [comment] 2016-02-02 05:06
Hi @thejameskyle, thank you for your report.

I tried your code with some versions of Node.js on Linux and Windows.
Then, I couldn't reproduce it till now. In these cases, the code works without problem (`^C` make the script stop without the process hanging).

### Node.js on Linux
- v0.10.35  OK
- v0.12.6   OK
- v2.3.1    OK
- v2.3.2    OK
- v3.0.0    OK
- v3.1.0    OK
- v3.2.0    OK
- v3.3.0    OK
- v3.3.1    OK
- v4.0.0    OK
- v4.2.1    OK
- v5.0.0    OK
- v5.5.0    OK

### Node.js on Windows
- v0.10.35  OK
- v0.12.0   OK
- v0.12.6   OK
- v2.3.0    OK
- v2.3.1    OK
- v2.3.2    OK
- v4.1.1    OK
- v4.2.1    OK
- v4.2.3    OK
- v4.2.4    OK
- v5.0.0    OK
- v5.1.0    OK
- v5.1.1    OK
- v5.5.0    OK

Could you tell me your environment?
Or, is this related to https://github.com/anseki/readline-sync/issues/7 ?

**Comment by anseki** [comment] 2016-02-09 03:27
There is no reply, and I close this issue.
If not solved, please reopen it.

**Closed by anseki** 2016-02-09 03:27 UTC

**Comment by thejameskyle** [comment] 2016-02-09 15:58
Oh I'm sorry I thought I had responded to this.

I'm on Mac OSX (Darwin) 10.11.3 with any version of node (I've tested 5.0.0, 4.2.2, 0.12.9).

**Comment by anseki** [comment] 2016-02-10 03:49
Hi @thejameskyle, thank you for the information.
Then, I couldn't reproduce it yet.
So, how did you make [your sample code](https://github.com/thejameskyle/__readline-sync-test) run? That is, is that a command such as `node thejameskyle/__readline-sync-test/index.js` in shell? Or not?
Might you possibly have used something such as signal-exit in another code?
