### ISSUE TITLE
No input received from terminal

### ISSUE THREAD

**Issue by espectalll123** [anseki/readline-sync#11] opened 2015-01-12 19:59 UTC
I'm developing a simple shell. Because I wanted the execution of code to be synced, input is managed through readline-sync. However, I've found that trying to do anything (including ^C or ^D) is useless. For example, a very basic code like:

    rl = require('readline-sync');
    input = rl.prompt();

keeps reading without ever responding. The same happens with other commands like `rl.question`. I can only guess that V8 is unable to receive any input, for some reason.

I'm running a manually compiled node.js 0.10.35 on Ubuntu 14.04 LTS, using Bash and the GNOME Terminal.

**Comment by anseki** [comment] 2015-01-13 02:17
Hi, Gomez
Does "keeps reading" mean that a method doesn't return? It's not that receiving a empty text from a method?
That is, The "NEXT LINE" isn't shown by this code?:

```js
var rl = require('readline-sync');
input = rl.prompt();
console.log('NEXT LINE');
```

**Comment by anseki** [comment] 2015-01-13 03:36
And, the prompt text (default: `>`) is shown?

**Comment by espectalll123** [comment] 2015-01-13 17:06
It stops executing at that point, trying to read input and keeping stuck. And the prompt is displayed correctly, so I am a 99'9% sure it has a problem with receiving input.

**Comment by anseki** [comment] 2015-01-14 10:01
Ummm... readlineSync works completely on my machine, there seems to be no problem.
(lubuntu-14.04.1, nodejs-v0.10.35, readline-sync-0.4.10)

The setup nodejs was no problem?
Because, I think that it's unusual that the `^C` doesn't work.

Try this:

1. Input below, and push enter key.

```shell
/bin/sh `node -e "console.log(require('path').dirname(require.resolve('readline-sync')))"`/read.sh
```

2. Type `abc`, and push enter key.
3. The `abc` is shown, and code is finished.

**Comment by espectalll123** [comment] 2015-01-14 16:00
That worked! Forgot to mention before - I had the problem *while using the Node interpreter*. So guess that's what happened. I was executing my code by invoking `require()` manually, and when I tried to debug, I never ran directly a script (take a look, I didn't use `var` to define a variable)

Now - could this bug be fixed? It seems that the problem is that node.js may be trying to read the input *twice*, in two different ways simultaneously. Or something like that.

**Comment by anseki** [comment] 2015-01-14 17:20
Ah, you tried in REPL. I understood.
The any codes that handles stdin don't work in REPL because REPL handles stdin (TTY). That is, it's like emulating the shell.
This is not bug. This is design of nodejs. And, nobody want input on REPL.

Try this code in REPL:

```js
process.stdin.pause()
```

**Comment by espectalll123** [comment] 2015-01-14 17:40
Ugh, I apologize. How simple. Guess I'll have to study better the APIs!

(and yup, here's someone who wants to read input from REPL. Working on what I consider a cool project. Hi!)

**Comment by espectalll123** [comment] 2015-01-14 18:52
Actually -- **not working**. It still keeps stuck. Here's the source code of the "real" thing:

```javascript
var os = require('os');
var rl = require('readline-sync');
var child_process = require('child_process');
var sh = require('execSync');

var username = sh.exec("id -un").stdout.replace(os.EOL, '');
var hostname = os.hostname();

module.exports = {
	shell: function (){
		console.log( 'Kuen Shell v0.0.1' );
		console.log( '2015 Francisco Gómez <espectalll123@outlook.com>' + os.EOL );
		
		process.stdin.pause()
		var loop = true;
		
		while(loop) {
			rl.setPrompt(username + '@' + hostname + ': ');
			input = rl.prompt();
			try {
				var shExec = sh.exec(input);
				console.log(shExec.stdout);
			} catch(e) {};
		};
	}
}
```

**Comment by anseki** [comment] 2015-01-15 09:22
If you want to read a line from another stream that is not REPL, I think that you must assign another channel (e.g. remote connection).
But, that idea is not good... Because the REPL is used for debug, that is a easy interactive environment. That will spoil REPL's good interactivity.
If you want to make the code run step by step for debug, the `node debug` might help you. Or, other debug tools like node-inspector.

So, your code seems to run with no problem in my machine. (some syntax errors are shown. but it's running.)
I tried input shell command (e.g. `ls`), then the response was shown at screen.
Doesn't `sh.exec()` method fail? because that depends on system environment.

Try this:

```js
var os = require('os');
var rl = require('readline-sync');
var child_process = require('child_process');
//var sh = require('execSync');
// Dummy Object
var sh = {exec: function(cmd) {
    return {stdout: 'Res of: ' + cmd};
}};

var username = sh.exec("id -un").stdout.replace(os.EOL, '');
var hostname = os.hostname();

module.exports = {
    shell: function (){
        console.log( 'Kuen Shell v0.0.1' );
        console.log( '2015 Francisco Gómez <espectalll123@outlook.com>' + os.EOL );

        process.stdin.pause();
        var loop = true;

        while(loop) {
            rl.setPrompt(username + '@' + hostname + ': ');
            input = rl.prompt();
            try {
                var shExec = sh.exec(input);
                console.log(shExec.stdout);
            } catch(e) {};
        };
    }
}
```

**Comment by anseki** [comment] 2015-01-15 09:37
I didn't try running readlineSync on `node debug`. That result might be same as REPL.

**Comment by anseki** [comment] 2015-01-24 08:52
10 days have passed. I think that that problem was already solved, and I close the issue.
If not solved, please reopen it.

**Closed by anseki** 2015-01-24 08:52 UTC

**Comment by espectalll123** [comment] 2015-01-28 17:36
The bug itself still happens. However, I'm going to try out a different workaround for my idea. Thanks!

**Comment by anseki** [comment] 2015-01-29 08:20
Ok. :blush:
If that bug you said is the bug of readlineSync, tell me please.

**Comment by anseki** [comment] 2018-07-31 11:46
Hi @CreeperDrop, thank you for the comment.

Yes, that is not a bug. It was clearly indicated that there was the problem in @espectalll's environment. (e.g. REPL)
